### ISSUE TITLE
Does logging persist on sleep/resume?

### ISSUE THREAD

**Issue by SillyKeith** [microsoft/busiotools#62]
I have an issue I need to reproduce across sleep/resume and the readme doesn't say if I need to use the "persist on reboot" method or the regular method.  Could you add a blurb about which method to use for capturing logs from a sleep/resume state?

**Comment by robert-wu-ms** [comment]
Updated the sensors tracing readme for more clarity here:

https://github.com/microsoft/busiotools/commit/1f11ff225106f118be714a862a56c7f1e919b1e1
